<?php

declare(strict_types=1);

return (new PhpCsFixer\Config())
    ->setRiskyAllowed(true)
    ->setRules([
        '@PSR12'                  => true,
        'align_multiline_comment' => true,
        'array_indentation'       => true,
        'array_syntax'            => ['syntax' => 'short'],
        'backtick_to_shell_exec'  => true,
        'binary_operator_spaces'  => ['default' => 'align_single_space_minimal', 'operators' => [
            '=' => 'align_single_space',
            '|' => 'single_space',
        ]],
        'blank_line_before_statement'             => true,
        'cast_spaces'                             => true,
        'class_attributes_separation'             => ['elements' => ['method' => 'one', 'property' => 'one', 'trait_import' => 'one']],
        'class_definition'                        => ['multi_line_extends_each_single_line' => true, 'single_item_single_line' => true],
        'clean_namespace'                         => true,
        'combine_consecutive_issets'              => true,
        'combine_consecutive_unsets'              => true,
        'combine_nested_dirname'                  => true,
        'comment_to_phpdoc'                       => true,
        'compact_nullable_typehint'               => true,
        'concat_space'                            => ['spacing' => 'one'],
        'control_structure_continuation_position' => true,
        'declare_parentheses'                     => true,
        'declare_strict_types'                    => true,
        'dir_constant'                            => true,
        'ereg_to_preg'                            => true,
        'escape_implicit_backslashes'             => true,
        'explicit_indirect_variable'              => true,
        'explicit_string_variable'                => true,
        'final_internal_class'                    => true,
        'fully_qualified_strict_types'            => true,
        'function_to_constant'                    => true,
        'function_typehint_space'                 => true,
        'general_phpdoc_annotation_remove'        => ['annotations' => ['class', 'package', 'author']],
        'general_phpdoc_tag_rename'               => true,
        'global_namespace_import'                 => false, // TODO: 2021.10.27 LaravelのFacadeと相性が悪いので一旦falseに変更（\Storage を use Storage にしてしまう）
        'heredoc_to_nowdoc'                       => true,
        'implode_call'                            => true,
        'include'                                 => true,
        'increment_style'                         => ['style' => 'post'],
        'integer_literal_case'                    => true,
        // 'is_null' => ['use_yoda_style' => false], TODO: 2018.8.23 is_null() 派が多いので一旦無効化
        'lambda_not_used_import'                      => true,
        'linebreak_after_opening_tag'                 => true,
        'list_syntax'                                 => true,
        'logical_operators'                           => true,
        'magic_constant_casing'                       => true,
        'magic_method_casing'                         => true,
        'method_chaining_indentation'                 => true,
        'modernize_strpos'                            => true,
        'modernize_types_casting'                     => true,
        'multiline_comment_opening_closing'           => true,
        'multiline_whitespace_before_semicolons'      => true,
        'native_function_casing'                      => true,
        'native_function_invocation'                  => ['scope' => 'namespaced', 'include' => ['@compiler_optimized']],
        'native_function_type_declaration_casing'     => true,
        'new_with_braces'                             => true,
        'no_alias_functions'                          => true,
        'no_alias_language_construct_call'            => true,
        'no_alternative_syntax'                       => true,
        'no_binary_string'                            => true,
        'no_blank_lines_after_class_opening'          => true,
        'no_blank_lines_after_phpdoc'                 => true,
        'no_empty_comment'                            => true,
        'no_empty_phpdoc'                             => true,
        'no_empty_statement'                          => true,
        'no_extra_blank_lines'                        => true,
        'no_homoglyph_names'                          => true,
        'no_leading_import_slash'                     => true,
        'no_leading_namespace_whitespace'             => true,
        'no_mixed_echo_print'                         => true,
        'no_multiline_whitespace_around_double_arrow' => true,
        'no_null_property_initialization'             => true,
        'no_php4_constructor'                         => true,
        'no_short_bool_cast'                          => true,
        'no_singleline_whitespace_before_semicolons'  => true,
        'no_spaces_around_offset'                     => true,
        'no_superfluous_elseif'                       => true,
        'no_trailing_comma_in_list_call'              => true,
        'no_trailing_comma_in_singleline_array'       => true,
        'no_unneeded_control_parentheses'             => ['statements' => ['break', 'clone', 'continue', 'echo_print', 'switch_case', 'yield']],
        'no_unneeded_curly_braces'                    => true,
        'no_unneeded_final_method'                    => true,
        'no_unreachable_default_argument_value'       => true,
        'no_unset_cast'                               => true,
        'no_unset_on_property'                        => true,
        'no_unused_imports'                           => true,
        'no_useless_else'                             => true,
        'no_useless_return'                           => true,
        'no_useless_sprintf'                          => true,
        'no_whitespace_before_comma_in_array'         => true,
        'no_whitespace_in_blank_line'                 => true,
        'normalize_index_brace'                       => true,
        // 'nullable_type_declaration_for_default_null_value' => true,
        'object_operator_without_whitespace' => true,
        // 'operator_linebreak' => true,
        'operator_linebreak'                     => ['only_booleans' => true, 'position' => 'end'],
        'ordered_class_elements'                 => true,
        'ordered_imports'                        => true,
        'php_unit_construct'                     => true,
        'php_unit_dedicate_assert'               => true,
        'php_unit_dedicate_assert_internal_type' => true,
        'php_unit_expectation'                   => true,
        'php_unit_fqcn_annotation'               => true,
        'php_unit_internal_class'                => true,
        'php_unit_mock'                          => true,
        'php_unit_mock_short_will_return'        => true,
        'php_unit_namespaced'                    => true,
        'php_unit_no_expectation_annotation'     => true,
        'php_unit_strict'                        => true,
        'php_unit_test_annotation'               => ['style' => 'annotation'],
        'php_unit_test_case_static_method_calls' => true,
        'phpdoc_add_missing_param_annotation'    => ['only_untyped' => false],
        'phpdoc_align'                           => ['tags' => ['param']],
        'phpdoc_annotation_without_dot'          => true,
        'phpdoc_indent'                          => true,
        'phpdoc_inline_tag_normalizer'           => true,
        'phpdoc_line_span'                       => true,
        'phpdoc_no_access'                       => true,
        // 'phpdoc_no_empty_return' => true,
        'phpdoc_no_package'                             => true,
        'phpdoc_no_useless_inheritdoc'                  => true,
        'phpdoc_return_self_reference'                  => true,
        'phpdoc_scalar'                                 => true,
        'phpdoc_separation'                             => true,
        'phpdoc_single_line_var_spacing'                => true,
        'phpdoc_tag_type'                               => true,
        'phpdoc_to_comment'                             => ['ignored_tags' => ['phpstan-ignore-next-line']],
        'phpdoc_trim'                                   => true,
        'phpdoc_trim_consecutive_blank_line_separation' => true,
        'phpdoc_types'                                  => true,
        'phpdoc_types_order'                            => ['null_adjustment' => 'always_last'],
        'phpdoc_var_annotation_correct_order'           => true,
        'phpdoc_var_without_name'                       => true,
        'pow_to_exponentiation'                         => true,
        'protected_to_private'                          => true,
        'random_api_migration'                          => true,
        'return_assignment'                             => true,
        'return_type_declaration'                       => true,
        'self_accessor'                                 => true,
        'semicolon_after_instruction'                   => true,
        'set_type_to_cast'                              => true,
        'short_scalar_cast'                             => true,
        'simple_to_complex_string_variable'             => true,
        // 'simplified_null_return' => true, TODO: 2021.10.06 return type hint がちゃんとしていないので無効化
        'single_line_comment_style'       => true,
        'single_quote'                    => true,
        'single_space_after_construct'    => true,
        'space_after_semicolon'           => true,
        'standardize_increment'           => true,
        'standardize_not_equals'          => true,
        'switch_continue_to_break'        => true,
        'ternary_to_null_coalescing'      => true,
        'trailing_comma_in_multiline'     => true,
        'trim_array_spaces'               => true,
        'types_spaces'                    => true,
        'unary_operator_spaces'           => true,
        'whitespace_after_comma_in_array' => true,
        'yoda_style'                      => ['equal' => false, 'identical' => false],
    ])
    ->setFinder(
        PhpCsFixer\Finder::create()
    ->exclude('vendor')
    ->in(__DIR__ . '/app')
    );
