name: reviewdog

on: [pull_request]

jobs:
  phpstan:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.1
          extensions: bcmath, mbstring, imagick, pcov
          tools: composer

      - name: Install reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Cache composer
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: |
            vendor
            tools
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Composer install
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: |
          composer install --prefer-dist

      - name: Run PHPStan
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./vendor/bin/phpstan analyse --error-format=raw --no-progress | reviewdog -reporter=github-pr-review -f=phpstan
